services:
  filmography-api:
    image: jsonserver
    container_name: filmography-api
    volumes:
      - ./db.json:/data/db.json
    ports:
      - "3000:3000"
    command: json-server --watch /data/db.json --host 0.0.0.0 --port 3000

  filmography-app:
    build: .
    ports:
      - "8080:80"
    restart: unless-stopped